-- Generated by octoui-dev recipe pipeline. Do not edit by hand.
-- Sources: TradeSkillsData(+turtle) and LibCrafts-1.0 by Refaim, pfQuest(+turtle)
-- by Shagu. See README.md for credits.

OctoUI_RecipeDB.recipes["Disguise"] = {
	{craft="Dalaran Wizard Disguise",id=5130,name="Knowledge: Dalaran Wizard Disguise",q=1,reagents={[2589]=1,[5110]=1},skill=1,spell=5267,vendor={npcs={50009}}},
	{craft="Dark Iron Dwarf Disguise",id=5129,name="Knowledge: Dark Iron Dwarf Disguise",q=1,reagents={[2592]=1,[5108]=1},skill=1,spell=5268,vendor={npcs={50007}}},
	{craft="Defias Disguise",id=5126,name="Knowledge: Defias Disguise",q=1,reagents={[2589]=1,[7997]=1},skill=1,spell=5169,vendor={npcs={50006}}},
	{craft="South Seas Pirate Disguise",id=5127,name="Knowledge: South Seas Pirate Disguise",q=1,reagents={[2589]=1,[5107]=1},skill=1,spell=5264,vendor={npcs={50008}}},
	{craft="Stonesplinter Trogg Disguise",id=5131,name="Knowledge: Stonesplinter Disguise",q=1,reagents={[2589]=1,[5109]=1},skill=1,spell=5265,vendor={npcs={50010}}},
	{craft="Syndicate Disguise",id=5132,name="Knowledge: Syndicate Disguise",q=1,reagents={[2592]=1,[5113]=1},skill=1,spell=5266,vendor={npcs={50011}}},
}
