-- Generated by octoui-dev recipe pipeline. Do not edit by hand.
-- Sources: TradeSkillsData(+turtle) and LibCrafts-1.0 by Refaim, pfQuest(+turtle)
-- by Shagu. See README.md for credits.

OctoUI_RecipeDB.recipes["Fishing"] = {
	{id=16083,name="Expert Fishing - The Bass and You",q=1,skill=125,tier=225,tierFrom=150,tierRank=3,vendor={npcs={2626},price=10000}},
}
