-- Generated by octoui-dev recipe pipeline. Do not edit by hand.
-- Sources: TradeSkillsData(+turtle) and LibCrafts-1.0 by Refaim, pfQuest(+turtle)
-- by Shagu. See README.md for credits.

OctoUI_RecipeDB.recipes["Mining"] = {
	{craft="Smelt Dreamsteel",id=61226,name="Book: Smelt Dreamsteel",q=2,quest={40886},reagents={[3859]=1,[20381]=1,[61198]=1},result=61216,skill=300,spell=45451},
}
