-- Generated by octoui-dev recipe pipeline. Do not edit by hand.
-- Sources: TradeSkillsData(+turtle) and LibCrafts-1.0 by Refaim, pfQuest(+turtle)
-- by Shagu. See README.md for credits.

OctoUI_RecipeDB.recipes["Poisons"] = {
	{craft="Deadly Poison V",drop={npcs={15339,15340,15341,15348,15369,15370}},id=21302,name="Handbook of Lethal Poisons",phase="AQ",q=3,reagents={[5173]=7,[8925]=1},result=20844,skill=300,spell=25347},
}
