-- Generated by octoui-dev recipe pipeline. Do not edit by hand.
-- Sources: TradeSkillsData(+turtle) and LibCrafts-1.0 by Refaim, pfQuest(+turtle)
-- by Shagu. See README.md for credits.

OctoUI_RecipeDB.recipes["Unknown"] = {
	{id=60779,name="Pattern: Depthstalker Helm"},
	{id=55042,name="Pattern: Harness of the High Thanes"},
	{id=55069,name="Pattern: Mantle of Falling Knives"},
	{id=55031,name="Pattern: Royal Robes of the Alteraci Princess"},
	{id=60998,name="Plans: Dark Iron Desecrator"},
	{id=55074,name="Plans: The Frigid Whisper"},
	{id=5641,name="Recipe: Cowardly Flight Potion"},
	{id=23690,name="Recipe: Crystal Flake Throat Lozenge"},
	{id=2556,name="Recipe: Elixir of Tongues"},
	{id=5657,name="Recipe: Instant Toxin"},
}
