-- Generated by octoui-dev recipe pipeline. Do not edit by hand.
-- Sources: TradeSkillsData(+turtle) and LibCrafts-1.0 by Refaim, pfQuest(+turtle)
-- by Shagu. See README.md for credits.

OctoUI_RecipeDB.recipes["Unknown"] = {
	{id=55076,name="Design: Carnelia's Sunset"},
	{id=70002,name="Formula: Enchant Gloves - Holy Power"},
	{id=6222,name="Formula: Imbue Chest - Minor Spirit"},
	{id=6343,name="Formula: Imbue Chest - Spirit"},
	{id=6345,name="Formula: Imbue Cloak - Protection"},
	{id=60779,name="Pattern: Depthstalker Helm"},
	{id=55042,name="Pattern: Harness of the High Thanes"},
	{id=55069,name="Pattern: Mantle of Falling Knives"},
	{id=55031,name="Pattern: Royal Robes of the Alteraci Princess"},
	{id=60998,name="Plans: Dark Iron Desecrator"},
	{id=55074,name="Plans: The Frigid Whisper"},
	{id=5641,name="Recipe: Cowardly Flight Potion"},
	{id=23690,name="Recipe: Crystal Flake Throat Lozenge"},
	{id=2556,name="Recipe: Elixir of Tongues"},
	{id=5657,name="Recipe: Instant Toxin"},
	{id=61392,name="Schematic: High Energy Regulator",object={ids={2020020},rates={[2020020]=100}}},
}
